{{
  config(
        tags=['piano']
    )
}}

with source as (
      select * from {{ source('piano', 'piano__vxsubscriptionlog') }}
),
renamed as (
    select
        {{ adapter.quote("Subscription_ID") }},
        {{ adapter.quote("Summary") }},
        {{ adapter.quote("Create_date") }},
        {{ adapter.quote("Start_date") }},
        {{ adapter.quote("End_date") }},
        {{ adapter.quote("Days_subscribed") }},
        {{ adapter.quote("Subscription_status") }},
        {{ adapter.quote("Upgrade_status") }},
        {{ adapter.quote("Trial_status") }},
        {{ adapter.quote("Trial_period_end_date") }},
        {{ adapter.quote("Trial_price") }},
        {{ adapter.quote("Regular_price") }},
        {{ adapter.quote("Auto_renew") }},
        {{ adapter.quote("Auto_renew_disablement_date") }},
        {{ adapter.quote("Last_active_date") }},
        {{ adapter.quote("Logins_last_30_days") }},
        {{ adapter.quote("Sessions_last_30_days") }},
        {{ adapter.quote("Pageviews_last_30_days") }},
        {{ adapter.quote("Billing_period") }},
        {{ adapter.quote("Total_charged") }},
        {{ adapter.quote("Charge_count") }},
        {{ adapter.quote("Total_refunded") }},
        {{ adapter.quote("Payment_source") }},
        {{ adapter.quote("Last_billing_date") }},
        {{ adapter.quote("Next_billing_date") }},
        {{ adapter.quote("Renewed") }},
        {{ adapter.quote("Currently_in_grace_period") }},
        {{ adapter.quote("Grace_period_start_date") }},
        {{ adapter.quote("Grace_period_extended_to") }},
        {{ adapter.quote("User_ID__UID_") }},
        {{ adapter.quote("User_email") }},
        {{ adapter.quote("First_name") }},
        {{ adapter.quote("Last_name") }},
        {{ adapter.quote("Access_expiration_date") }},
        {{ adapter.quote("Resource_ID__RID_") }},
        {{ adapter.quote("Resource_name") }},
        {{ adapter.quote("Term_ID") }},
        {{ adapter.quote("Term_name") }},
        {{ adapter.quote("Term_type") }},
        {{ adapter.quote("Template_ID") }},
        {{ adapter.quote("Template_name") }},
        {{ adapter.quote("Offer_ID") }},
        {{ adapter.quote("Offer_name") }},
        {{ adapter.quote("Experience_ID") }},
        {{ adapter.quote("Experience_name") }},
        {{ adapter.quote("Campaign_codes") }},
        {{ adapter.quote("Promo_code") }},
        {{ adapter.quote("Conversion_city") }},
        {{ adapter.quote("Conversion_state") }},
        {{ adapter.quote("Conversion_country") }},
        {{ adapter.quote("Device") }},
        {{ adapter.quote("URL") }},
        {{ adapter.quote("Cleaned_URL") }},
        {{ adapter.quote("UTM_parameters") }},
        {{ adapter.quote("Name__first_and_last_") }},
        {{ adapter.quote("Company_name") }},
        {{ adapter.quote("Address_1") }},
        {{ adapter.quote("Address_2") }},
        {{ adapter.quote("Address_city") }},
        {{ adapter.quote("Address_state") }},
        {{ adapter.quote("Address_country") }},
        {{ adapter.quote("Postal_code") }},
        {{ adapter.quote("Phone") }},
        {{ adapter.quote("PSC_subscriber_number") }},
        {{ adapter.quote("Tax") }},
        {{ adapter.quote("Tax_base") }},
        {{ adapter.quote("Tax_rate") }},
        {{ adapter.quote("Tax_country") }},
        {{ adapter.quote("Tax_state_province") }},
        {{ adapter.quote("Billing_postal_code") }},
        {{ adapter.quote("Shared_subscriptions") }},
        {{ adapter.quote("Migrated_to_Piano") }},
        {{ adapter.quote("Migrated_date") }},
        {{ adapter.quote("Created_via_upgrade") }},
        {{ adapter.quote("Upgrade_from___subscription_ID") }},
        {{ adapter.quote("Period_name") }},
        {{ adapter.quote("Access_period") }},
        {{ adapter.quote("Period_count") }},
        {{ adapter.quote("report_type") }},
        {{ adapter.quote("app_id") }},
        {{ adapter.quote("app_name") }},
        {{ adapter.quote("record_load_dts") }}

    from source
)
select * from renamed
