SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DeleteSCVFromStaging] AS

DELETE FROM [dbo].[SCV]
      WHERE [Unique ID] IN (SELECT [Unique ID] FROM dbo.SCV_DELETE_STAGING)
;

TRUNCATE table dbo.SCV_DELETE_STAGING;


GO
