SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SCV_UpsertDeltaRecord] AS
MERGE [dbo].SCV AS [Target]
  USING (SELECT * from [dbo].SCV_Staging) AS [Source]
    ON [Target].[Unique ID] = [Source].[Unique ID]
  WHEN MATCHED THEN
       UPDATE SET
          [Unique ID] = [Source].[Unique ID]
		,[DataSource]  = [Source].[DataSource]
		,[IKEY Cluster ID] = CASE WHEN [Source].[IKEY Cluster ID] IS NULL THEN [Target].[IKEY Cluster ID] ELSE [Source].[IKEY Cluster ID] END
		,[IKEY Match status] =  CASE WHEN [Source].[IKEY Cluster ID] IS NULL THEN [Target].[IKEY Match status] ELSE [Source].[IKEY Match status] END
		,[AKEY Cluster ID] = CASE WHEN [Source].[AKEY Cluster ID] IS NULL THEN [Target].[AKEY Cluster ID] ELSE [Source].[AKEY Cluster ID] END
		,[AKEY Match status] =  CASE WHEN [Source].[AKEY Cluster ID] IS NULL THEN [Target].[AKEY Match status] ELSE [Source].[AKEY Match status] END
		,[Type]  = [Source].[Type]
		,[Status]  = [Source].[Status]
		,[Title]  = [Source].[Title]
		,[First Name]  = [Source].[First Name]
		,[Middle Name]  = [Source].[Middle Name]
		,[Last Name]  = [Source].[Last Name]
		,[Date of Birth] = [Source].[Date of Birth]
		,[Phone 1]  = [Source].[Phone 1]
		,[Phone 2]  = [Source].[Phone 2]
		,[Phone 3]  = [Source].[Phone 3]
		,[Email 1]  = [Source].[Email 1]
		,[Email 2]  = [Source].[Email 2]
		,[Email 3]  = [Source].[Email 3]
		,[Address 1 Type]  = [Source].[Address 1 Type]
		,[Address 1 Line 1]  = [Source].[Address 1 Line 1]
		,[Address 1 Line 2]  = [Source].[Address 1 Line 2]
		,[Address 1 Suburb]  = [Source].[Address 1 Suburb]
		,[Address 1 City]  = [Source].[Address 1 City]
		,[Address 1 Postcode]  = [Source].[Address 1 Postcode]
		,[Address 1 Country]  = [Source].[Address 1 Country]
		,[Address 1 Dpid]  = [Source].[Address 1 Dpid]
		,[Address 1 Latitude]  = [Source].[Address 1 Latitude]
		,[Address 1 Longitude]  = [Source].[Address 1 Longitude]
		,[Address 1 X Coordinate]  = [Source].[Address 1 X Coordinate]
		,[Address 1 Y Coordinate]  = [Source].[Address 1 Y Coordinate]
		,[Address 1 Mosaic Type]  = [Source].[Address 1 Mosaic Type]
		,[Address 2 Type]  = [Source].[Address 2 Type]
		,[Address 2 Line 1]  = [Source].[Address 2 Line 1]
		,[Address 2 Line 2]  = [Source].[Address 2 Line 2]
		,[Address 2 Line 3]  = [Source].[Address 2 Line 3]
		,[Address 2 Suburb]  = [Source].[Address 2 Suburb]
		,[Address 2 City]  = [Source].[Address 2 City]
		,[Address 2 Postcode]  = [Source].[Address 2 Postcode]
		,[Address 2 Country]  = [Source].[Address 2 Country]
		,[Address 2 Dpid]  = [Source].[Address 2 Dpid]
		,[Address 2 X Coordinate]  = [Source].[Address 2 X Coordinate]
		,[Address 2 Y Coordinate]  = [Source].[Address 2 Y Coordinate]
		,[Address 2 Mosaic Type]  = [Source].[Address 2 Mosaic Type]
		,[Email 1 Domain Result]  = [Source].[Email 1 Domain Result]
		,[Email 2 Domain Result]  = [Source].[Email 2 Domain Result]
		,[Email 3 Domain Result]  = [Source].[Email 3 Domain Result]
		,[Valid Phone 1]  = [Source].[Valid Phone 1]
		,[Valid Phone 2]  = [Source].[Valid Phone 2]
		,[Valid Phone 3]  = [Source].[Valid Phone 3]
		,[Validate Address 1 MatchResultCode]  = [Source].[Validate Address 1 MatchResultCode]
		,[Validate Address 2 MatchResultCode]  = [Source].[Validate Address 2 MatchResultCode]
		,[Do Not Mail]  = [Source].[Do Not Mail]
		,[Do Not Call]  = [Source].[Do Not Call]
		,[Age]  = [Source].[Age]
		,[Deceased]  = [Source].[Deceased]
		,[Last Contact Date] = [Source].[Last Contact Date]
		,[Supress YN]  = [Source].[Supress YN]
		,[Supress Reason]   = [Source].[Supress Reason]
		,[Not Individual]   = [Source].[Not Individual]
		,[Hash Diff]  = [Source].[Hash Diff]
		,[Customer Hash]  = [Source].[Customer Hash]
		,[Record Load Dts] = [Source].[Record Load Dts]
		,[Record Load End Dts] = [Source].[Record Load End Dts]
		,[Active]  = [Source].[Active]
		,[Dominion_Post]  = [Source].[Dominion_Post]
		,[The_Press]  = [Source].[The_Press]
		,[Waikato_Times]  = [Source].[Waikato_Times]
		,[Southland_Times]  = [Source].[Southland_Times]
		,[Taranaki_Daily_News]  = [Source].[Taranaki_Daily_News]
		,[Manawatu_Standard]  = [Source].[Manawatu_Standard]
		,[Nelson_Mail]  = [Source].[Nelson_Mail]
		,[Timaru_Herald]  = [Source].[Timaru_Herald]
		,[The_Marlborough_Express]  = [Source].[The_Marlborough_Express]
		,[Sunday_Star_Times]  = [Source].[Sunday_Star_Times]
		,[Sunday_News]  = [Source].[Sunday_News]
		,[NZ_House_Garden]  = [Source].[NZ_House_Garden]
		,[NZ_Gardener]  = [Source].[NZ_Gardener]
		,[TV_Guide]  = [Source].[TV_Guide]
		,[Fibre_Active]  = [Source].[Fibre_Active]
		,[Neighbourly_Member]  = [Source].[Neighbourly_Member]
		,[Create Date] = [Source].[Create Date]
		,[Last Update Date] = [Source].[Last Update Date]
		,[Subscriber] = [Source].[Subscriber]

  WHEN NOT MATCHED THEN
       INSERT ([Unique ID]
		, [DataSource]
		, [IKEY Cluster ID]
		, [IKEY Match status]
		, [AKEY Cluster ID]
		, [AKEY Match status]
		, [Type]
		, [Status]
		, [Title]
		, [First Name]
		, [Middle Name]
		, [Last Name]
		, [Date of Birth]
		, [Phone 1]
		, [Phone 2]
		, [Phone 3]
		, [Email 1]
		, [Email 2]
		, [Email 3]
		, [Address 1 Type]
		, [Address 1 Line 1]
		, [Address 1 Line 2]
		, [Address 1 Suburb]
		, [Address 1 City]
		, [Address 1 Postcode]
		, [Address 1 Country]
		, [Address 1 Dpid]
		, [Address 1 Latitude]
		, [Address 1 Longitude]
		, [Address 1 X Coordinate]
		, [Address 1 Y Coordinate]
		, [Address 1 Mosaic Type]
		, [Address 2 Type]
		, [Address 2 Line 1]
		, [Address 2 Line 2]
		, [Address 2 Line 3]
		, [Address 2 Suburb]
		, [Address 2 City]
		, [Address 2 Postcode]
		, [Address 2 Country]
		, [Address 2 Dpid]
		, [Address 2 X Coordinate]
		, [Address 2 Y Coordinate]
		, [Address 2 Mosaic Type]
		, [Email 1 Domain Result]
		, [Email 2 Domain Result]
		, [Email 3 Domain Result]
		, [Valid Phone 1]
		, [Valid Phone 2]
		, [Valid Phone 3]
		, [Validate Address 1 MatchResultCode]
		, [Validate Address 2 MatchResultCode]
		, [Do Not Mail]
		, [Do Not Call]
		, [Age]
		, [Deceased]
		, [Last Contact Date]
		, [Supress YN]
		, [Supress Reason]
		, [Not Individual]
		, [Hash Diff]
		, [Customer Hash]
		, [Record Load Dts]
		, [Record Load End Dts]
		, [Active]
		, [Dominion_Post]
		, [The_Press]
		, [Waikato_Times]
		, [Southland_Times]
		, [Taranaki_Daily_News]
		, [Manawatu_Standard]
		, [Nelson_Mail]
		, [Timaru_Herald]
		, [The_Marlborough_Express]
		, [Sunday_Star_Times]
		, [Sunday_News]
		, [NZ_House_Garden]
		, [NZ_Gardener]
		, [TV_Guide]
		, [Fibre_Active]
		, [Neighbourly_Member]
		, [Create Date]
		, [Last Update Date]
		, [Subscriber]

)
        VALUES ([Source].[Unique ID]
		, [Source].[DataSource]
		, [Source].[IKEY Cluster ID]
		, [Source].[IKEY Match status]
		, [Source].[AKEY Cluster ID]
		, [Source].[AKEY Match status]
		, [Source].[Type]
		, [Source].[Status]
		, [Source].[Title]
		, [Source].[First Name]
		, [Source].[Middle Name]
		, [Source].[Last Name]
		, [Source].[Date of Birth]
		, [Source].[Phone 1]
		, [Source].[Phone 2]
		, [Source].[Phone 3]
		, [Source].[Email 1]
		, [Source].[Email 2]
		, [Source].[Email 3]
		, [Source].[Address 1 Type]
		, [Source].[Address 1 Line 1]
		, [Source].[Address 1 Line 2]
		, [Source].[Address 1 Suburb]
		, [Source].[Address 1 City]
		, [Source].[Address 1 Postcode]
		, [Source].[Address 1 Country]
		, [Source].[Address 1 Dpid]
		, [Source].[Address 1 Latitude]
		, [Source].[Address 1 Longitude]
		, [Source].[Address 1 X Coordinate]
		, [Source].[Address 1 Y Coordinate]
		, [Source].[Address 1 Mosaic Type]
		, [Source].[Address 2 Type]
		, [Source].[Address 2 Line 1]
		, [Source].[Address 2 Line 2]
		, [Source].[Address 2 Line 3]
		, [Source].[Address 2 Suburb]
		, [Source].[Address 2 City]
		, [Source].[Address 2 Postcode]
		, [Source].[Address 2 Country]
		, [Source].[Address 2 Dpid]
		, [Source].[Address 2 X Coordinate]
		, [Source].[Address 2 Y Coordinate]
		, [Source].[Address 2 Mosaic Type]
		, [Source].[Email 1 Domain Result]
		, [Source].[Email 2 Domain Result]
		, [Source].[Email 3 Domain Result]
		, [Source].[Valid Phone 1]
		, [Source].[Valid Phone 2]
		, [Source].[Valid Phone 3]
		, [Source].[Validate Address 1 MatchResultCode]
		, [Source].[Validate Address 2 MatchResultCode]
		, [Source].[Do Not Mail]
		, [Source].[Do Not Call]
		, [Source].[Age]
		, [Source].[Deceased]
		, [Source].[Last Contact Date]
		, [Source].[Supress YN]
		, [Source].[Supress Reason]
		, [Source].[Not Individual]
		, [Source].[Hash Diff]
		, [Source].[Customer Hash]
		, [Source].[Record Load Dts]
		, [Source].[Record Load End Dts]
		, [Source].[Active]
		, [Source].[Dominion_Post]
		, [Source].[The_Press]
		, [Source].[Waikato_Times]
		, [Source].[Southland_Times]
		, [Source].[Taranaki_Daily_News]
		, [Source].[Manawatu_Standard]
		, [Source].[Nelson_Mail]
		, [Source].[Timaru_Herald]
		, [Source].[The_Marlborough_Express]
		, [Source].[Sunday_Star_Times]
		, [Source].[Sunday_News]
		, [Source].[NZ_House_Garden]
		, [Source].[NZ_Gardener]
		, [Source].[TV_Guide]
		, [Source].[Fibre_Active]
		, [Source].[Neighbourly_Member]
		, [Source].[Create Date]
		, [Source].[Last Update Date]
		, [Source].[Subscriber]

);

UPDATE [dbo].SCV
SET
       [dbo].SCV.[IKEY Cluster ID]             = [delta].SCV_Ikey.[IKEY Cluster ID],
       [dbo].SCV.[IKEY Match status] = [delta].SCV_Ikey.[IKEY Match status],
	   [dbo].SCV.[Last Update Date]	=	[delta].SCV_Ikey.[Last Update Date]
FROM [dbo].SCV
       INNER JOIN  [delta].[SCV_Ikey]

ON [dbo].SCV.[Unique ID] = [delta].SCV_Ikey.[Unique ID];

UPDATE [dbo].SCV
SET
       [dbo].SCV.[AKEY Cluster ID]            = [delta].SCV_Akey.[AKEY Cluster ID],
       [dbo].SCV.[AKEY Match status] = [delta].SCV_Akey.[AKEY Match status],
	   [dbo].SCV.[Last Update Date]	=	[delta].SCV_Akey.[Last Update Date]
FROM [dbo].SCV
       INNER JOIN  [delta].[SCV_Akey]

ON [dbo].SCV.[Unique ID] = [delta].SCV_Akey.[Unique ID];
GO
