name: hexa-data-alteryx-workflows-cd

parameters:
  - name: dockerSubdirectory
    displayName: 'Docker Subdirectory Name'
    type: string
    default: 'docker-eks-test'
    values:
    - docker-eks-test
    - brightcove-workflow
    - naviga-workflow
    - idm-bigquery
    - adobe-workflow
    - matrix-workflow
    - piano-workflow
    - sentiment-workflow
    - source-freshness
    - presspatron-workflow
    - replatform-workflow
    - matrix-dbt
    - showcase-workflow
    - megaphone-workflow
    - neighbourly-workflow
    - brightcove
    - gam-dbt
    - hexaevent
    - admanager-workflow
    - infosum-workflow
    - ga-workflow
    - smi-workflow
    - bonzai-workflow

  - name: Environment
    displayName: 'Deploying to'
    type: string
    default: 'dev.hexa-data-migration'
    values:
    - dev.hexa-data-migration
    - dev.hexa-web-and-apps-dev
    - prod.hexa-web-and-apps

trigger: none

pr:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - '*'

resources:
  pipelines:
  - pipeline: hexa-data-alteryx-workflows-ci
    source: hexa-data-alteryx-workflows-ci
    trigger:
      branches:
        include:
        - main
  repositories:
    - repository: templates
      type: github
      name: hexaNZ/hexa-azure-pipeline-templates
      endpoint: hexaNZ
      ref: refs/tags/9.2

extends:
  template: deploy/hexa-helm-job.yaml@templates
  parameters:
    deploymentPackagePath: $(Pipeline.Workspace)/hexa-data-alteryx-workflows-ci/deployment-package
    helmChartName: "hexa-nebula-helm/cronjob2"
    helmChartVersion: '0.0.3'
    environmentResource: dev.hexa-data-migration
    helmValueFile: "helm/values.yaml"
    helmArguments: "--set image.tag=${{ parameters.dockerSubdirectory }}-latest"
    releaseName: "$(PROJECT_KEY)-${{ parameters.dockerSubdirectory }}"
