{{
  config(
        tags=['lookup','gam'],
        materialized='table'
    )
}}

WITH mappings AS (

    SELECT * FROM {{ ref('groupm_postcodes__new_segments') }}

)

SELECT postcode as POSTCODE
    , CASE WHEN MAX(`101-BlueChip`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_BLUECHIP
    , CASE WHEN MAX(`102-Smart Money`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_SMARTMONEY
    , CASE WHEN MAX(`103-Financial Freedom`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_FINANCIALFREEDOM
    , CASE WHEN MAX(`104-Self Made Lifestylers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_SELFMADLIFESTYLERS
    , CASE WHEN MAX(`105-Worldly and Wise`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_WORLDLYANDWISE
    , CASE WHEN MAX(`106-Status Matters`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_STATUSMATTERS
    , CASE WHEN MAX(`107-Savvy Self Starters`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_SAVVYSELFSTARTERS
    , CASE WHEN MAX(`108-Humanitarians`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_HUMANITARIANS
    , CASE WHEN MAX(`109-Full House`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_FULLHOUSE
    , CASE WHEN MAX(`201-Young and Platinum`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_YOUNGANDPLATINUM
    , CASE WHEN MAX(`202-Healthy Wealthy and Wise`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_HEALTHYWEALTHYANDWISE
    , CASE WHEN MAX(`203-Cultural Pioneers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_CULTURALPIONEERS
    , CASE WHEN MAX(`204-New School Cool`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_NEWSCHOOLCOOL
    , CASE WHEN MAX(`205-Urban Entertainers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_URBANENTERTAINERS
    , CASE WHEN MAX(`206-New Kiwis`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_NEWKIWIS
    , CASE WHEN MAX(`207-Social Academics`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_SOCIALACADEMICS
    , CASE WHEN MAX(`208-Big Future`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_BIGFUTURE
    , CASE WHEN MAX(`209-Fit and Fab`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_FITANDFAB
    , CASE WHEN MAX(`210-Quiet Achiever`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_QUIETACHIEVER
    , CASE WHEN MAX(`301-Career Zone`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_CAREERZONE
    , CASE WHEN MAX(`302-On Their Way`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_ONTHEIRWAY
    , CASE WHEN MAX(`303-Getting Ahead`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_GETTINGAHEAD
    , CASE WHEN MAX(`304-Domestic Jugglers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_DOMESTICJUGGLERS
    , CASE WHEN MAX(`305-Average Kiwi`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_AVERAGEKIWI
    , CASE WHEN MAX(`306-Down To Earth`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_DOWNTHEARTH
    , CASE WHEN MAX(`401-Domestic Bliss`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_DOMESTICBLISS
    , CASE WHEN MAX(`402-Done Good`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_DONEGOOD
    , CASE WHEN MAX(`403-Traditional Values`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_TRADITIONALVALUES
    , CASE WHEN MAX(`404-Castle and Kids`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_CASTLEANDKIDS
    , CASE WHEN MAX(`405-House Proud`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_HOUSEPROUD
    , CASE WHEN MAX(`406-Family First`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_FAMILYFIRST
    , CASE WHEN MAX(`407-Relaxed Living`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_RELAXEDLIVING
    , CASE WHEN MAX(`408-Cautious Conservatives`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_CAUTIOUSCONSERVATIVES
    , CASE WHEN MAX(`501-Making the Rent`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_MAKINGTHERENT
    , CASE WHEN MAX(`502-Making Ends Meet`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_MAKINGENDSMEET
    , CASE WHEN MAX(`503-Doing It Tough`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_DOINGITTOUGH
    , CASE WHEN MAX(`504-Life Strivers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_LIFESTRIVERS
    , CASE WHEN MAX(`505-Active Social`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_ACTIVESOCIAL
    , CASE WHEN MAX(`506-Home Entertainment`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_HOMEENTERTAINMENT
    , CASE WHEN MAX(`507-Better Days`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_BETTERDAYS
    , CASE WHEN MAX(`508-Faith & Family`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_FAITHANDFAMILY
    , CASE WHEN MAX(`509-Simple Living`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_SIMPLELIVING
    , CASE WHEN MAX(`510-Quiet Home Life`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_QUIETHOMELIFE
    , CASE WHEN MAX(`601-Areas in Transition`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_AREASINTRANSITION
    , CASE WHEN MAX(`602-Still Working`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_STILLWORKING
    , CASE WHEN MAX(`603-New Beginnings`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_NEWBEGINNINGS
    , CASE WHEN MAX(`604-Struggle Street`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_STRUGGLESTREET
    , CASE WHEN MAX(`605-Coupon Clippers`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_COUPONCLIPPERS
    , CASE WHEN MAX(`606-Penny Wise`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_PENNYWISE
    , CASE WHEN MAX(`607-Real Working`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_REALWORKING
    , CASE WHEN MAX(`608-Budget Living`) = 1 THEN TRUE ELSE FALSE END AS GROUPM_BUDGETLIVING
FROM mappings
GROUP BY 1
