
WITH date_series AS (

  SELECT DATE_ADD(DATE '2010-01-01', INTERVAL x DAY) AS DATE
  FROM UNNEST(GENERATE_ARRAY(0, DATE_DIFF(CURRENT_DATE(), DATE '2010-01-01', DAY), 1)) AS x

),

date_info AS (

  SELECT DATE
    , FORMAT_DATETIME('%A', DATETIME(DATE)) AS DAY_OF_WEEK
    , FORMAT_DATETIME('%a', DATETIME(DATE)) AS DAY_OF_WEEK_ABBR
    , FORMAT_DATETIME('%B', DATETIME(DATE)) AS MONTH_NAME
    , EXTRACT(ISOWEEK FROM DATE) AS ISO_WEEK_NUMBER
    , EXTRACT(MONTH FROM DATE) AS MONTH
    , CASE WHEN EXTRACT(DAYOFWEEK FROM DATE) BETWEEN 2 AND 6 THEN TRUE
      ELSE FALSE END AS IS_WEEKDAY
    , CASE WHEN EXTRACT(MONTH FROM DATE) BETWEEN 7 AND 12 THEN EXTRACT(YEAR FROM DATE) + 1
      ELSE EXTRACT(YEAR FROM DATE) END AS FINANCIAL_YEAR
    , CASE WHEN EXTRACT(MONTH FROM DATE) BETWEEN 7 AND 9 THEN 1
      WHEN EXTRACT(MONTH FROM DATE) BETWEEN 10 AND 12 THEN 2
      WHEN EXTRACT(MONTH FROM DATE) BETWEEN 1 AND 3 THEN 3
      WHEN EXTRACT(MONTH FROM DATE) BETWEEN 4 AND 6 THEN 4
      END AS FINANCIAL_QUARTER
    , CASE WHEN EXTRACT(MONTH FROM DATE) BETWEEN 7 AND 12 THEN EXTRACT(MONTH FROM DATE) - 6
      ELSE EXTRACT(MONTH FROM DATE) + 6 END AS FINANCIAL_MONTH
  FROM date_series

)

SELECT * FROM date_info
